ALTER TABLE chargers DROP CONSTRAINT chk_chargers_status;
ALTER TABLE connectors DROP CONSTRAINT chk_connectors_status;

ALTER TABLE chargers ALTER COLUMN status SET DEFAULT 'INACTIVE';
ALTER TABLE connectors ALTER COLUMN status SET DEFAULT 'INACTIVE';

UPDATE chargers
SET status = CASE status
    WHEN 'AVAILABLE' THEN 'ACTIVE'
    WHEN 'PREPARING' THEN 'ACTIVE'
    WHEN 'CHARGING' THEN 'ACTIVE'
    WHEN 'FINISHING' THEN 'ACTIVE'
    WHEN 'RESERVED' THEN 'ACTIVE'
    WHEN 'SUSPENDED_EV' THEN 'SUSPENDED'
    WHEN 'SUSPENDED_EVSE' THEN 'SUSPENDED'
    WHEN 'FAULTED' THEN 'UNDERMAINTENANCE'
    WHEN 'UNAVAILABLE' THEN 'INACTIVE'
    WHEN 'OFFLINE' THEN 'INACTIVE'
END;

UPDATE connectors
SET status = CASE status
    WHEN 'AVAILABLE' THEN 'ACTIVE'
    WHEN 'PREPARING' THEN 'ACTIVE'
    WHEN 'CHARGING' THEN 'ACTIVE'
    WHEN 'FINISHING' THEN 'ACTIVE'
    WHEN 'RESERVED' THEN 'ACTIVE'
    WHEN 'SUSPENDED_EV' THEN 'SUSPENDED'
    WHEN 'SUSPENDED_EVSE' THEN 'SUSPENDED'
    WHEN 'FAULTED' THEN 'UNDERMAINTENANCE'
    WHEN 'UNAVAILABLE' THEN 'INACTIVE'
    WHEN 'OFFLINE' THEN 'INACTIVE'
END;

ALTER TABLE chargers ADD CONSTRAINT chk_chargers_status CHECK (
    status IN (
        'ACTIVE',
        'INACTIVE',
        'SUSPENDED',
        'UNDERMAINTENANCE',
        'DECOMMISSIONED'
    )
);
ALTER TABLE connectors ADD CONSTRAINT chk_connectors_status CHECK (
    status IN (
        'ACTIVE',
        'INACTIVE',
        'SUSPENDED',
        'UNDERMAINTENANCE',
        'DECOMMISSIONED'
    )
);
