ALTER TABLE chargers
    ADD COLUMN IF NOT EXISTS charger_name VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS charger_host_name VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS charger_host_phone_no VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS charger_type VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS segment VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS sub_segment VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS total_capacity NUMERIC(10, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS charger_image TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS charger_use_type VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS number_of_connectors INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS parking VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS protocol VARCHAR(50) NOT NULL DEFAULT 'OCPP 1.6J',
    ADD COLUMN IF NOT EXISTS twenty_four_seven_open_status BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE connectors
    ADD COLUMN IF NOT EXISTS connector_max_capacity NUMERIC(10, 2) NOT NULL DEFAULT 0;
