DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM support_tickets WHERE channel = 'CUSTOMER_CPO') THEN
        RAISE EXCEPTION 'cannot roll back migration 72 while CUSTOMER_CPO support history exists';
    END IF;
    IF EXISTS (SELECT 1 FROM mail_outbox WHERE template IN ('CUSTOMER_CPO_SUPPORT_TICKET_CREATED','CUSTOMER_CPO_SUPPORT_TICKET_REPLY','CUSTOMER_CPO_SUPPORT_TICKET_STATUS_CHANGED')) THEN
        RAISE EXCEPTION 'cannot roll back migration 72 while customer support mail intents exist';
    END IF;
END $$;
ALTER TABLE support_ticket_events DROP CONSTRAINT IF EXISTS chk_support_ticket_events_actor, DROP CONSTRAINT IF EXISTS fk_support_ticket_events_customer, DROP COLUMN actor_customer_id;
ALTER TABLE support_ticket_messages DROP CONSTRAINT IF EXISTS chk_support_ticket_messages_actor, DROP CONSTRAINT IF EXISTS chk_support_ticket_messages_scope, DROP CONSTRAINT IF EXISTS fk_support_ticket_messages_customer, ALTER COLUMN author_user_id SET NOT NULL, DROP COLUMN author_customer_id, ADD CONSTRAINT chk_support_ticket_messages_scope CHECK (author_scope IN ('CPO', 'PLATFORM'));
ALTER TABLE support_tickets DROP CONSTRAINT IF EXISTS chk_support_tickets_channel_actor, DROP CONSTRAINT IF EXISTS fk_support_tickets_customer_cpo, DROP CONSTRAINT IF EXISTS chk_support_tickets_channel, ALTER COLUMN created_by_user_id SET NOT NULL, DROP COLUMN customer_id, DROP COLUMN channel;
ALTER TABLE mail_outbox DROP CONSTRAINT IF EXISTS chk_mail_outbox_template;
ALTER TABLE mail_outbox ADD CONSTRAINT chk_mail_outbox_template CHECK (template IN ('LOGIN_OTP','PASSWORD_RESET_OTP','CUSTOMER_LOGIN_OTP','CUSTOMER_SIGNUP_OTP','CUSTOMER_PASSWORD_RESET_OTP','CPO_ADMIN_WELCOME','CPO_MEMBERSHIP_ASSIGNED','PASSWORD_CHANGE_REMINDER','PLATFORM_ADMIN_INVITE','PLATFORM_ADMIN_GRANTED','CPO_STAFF_NEW_IDENTITY','CPO_STAFF_EXISTING_IDENTITY','CPO_ONBOARDING_RESENT','CPO_STAFF_ROLE_CHANGED','CPO_STAFF_SUSPENDED','CPO_STAFF_REACTIVATED','CPO_STAFF_REVOKED','CPO_SUBSCRIPTION_EXPIRY_WARNING','CPO_SUBSCRIPTION_EXPIRED','CPO_SUPPORT_TICKET_CREATED','CPO_SUPPORT_TICKET_PLATFORM_REPLY','CPO_SUPPORT_TICKET_RESOLVED','CPO_SUPPORT_TICKET_CLOSED','CPO_SUPPORT_TICKET_REOPENED')) NOT VALID;
